---
abstract: 'A Task module for DWIM Perl L<http://dwimperl.com/>'
author:
  - 'Gabor Szabo <szabgab@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Task-DWIM
no_index:
  directory:
    - inc
    - t
requires:
  Algorithm::C3: 0.08
  Algorithm::Diff: 1.1902
  Any::Moose: 0.18
  App::Ack: 1.96
  App::Cmd::Setup: 0.316
  App::cpanminus: 1.5007
  App::cpanoutdated: 0.20
  App::pmuninstall: 0.29
  AppConfig: 1.66
  Archive::Tar: 1.80
  Archive::Zip: 1.30
  Attribute::Handlers: 0.91
  B::Deparse: 0
  B::Hooks::EndOfScope: 0.11
  B::Hooks::OP::Check: 0.19
  B::Hooks::OP::PPAddr: 0.03
  B::Keywords: 1.12
  B::Utils: 0.19
  Bencode: 1.4
  Browser::Open: 0.04
  CGI: 3.58
  CGI::FormBuilder::Source::Perl: 0
  CGI::Simple::Cookie: 1.113
  CHI: 0
  CPAN::DistnameInfo: 0.12
  CPAN::Inject: 1.13
  CPAN::Meta: 2.112621
  CPAN::Meta::Requirements: 2.120351
  CPAN::Meta::YAML: 0.004
  CPAN::Reporter: 1.2003
  CPAN::SQLite: 0.202
  CPAN::Testers::Report: 1.999001
  CPAN::Uploader: 0.103000
  CPANPLUS: 0.9112
  CPANPLUS::Dist::Build: 0.60
  CSS::Tiny: 1.19
  Cache::Cache: 1.06
  Capture::Tiny: 0.15
  Carp: 1.23
  Carp::Always: 0
  Carp::Assert: 0.20
  Carp::Assert::More: 1.12
  Carp::Clan: 6.04
  Catalyst: 5.90011
  Catalyst::Action::REST: 0.99
  Catalyst::Action::RenderView: 0.16
  Catalyst::ActionRole::ACL: 0.06
  Catalyst::Authentication::Credential::HTTP: 1.014
  Catalyst::Authentication::Store::DBIx::Class: 0
  Catalyst::Component::InstancePerContext: 0
  Catalyst::Controller::ActionRole: 0.15
  Catalyst::Devel: 1.36
  Catalyst::Manual: 5.9003
  Catalyst::Model::Adaptor: 0
  Catalyst::Model::DBIC::Schema: 0
  Catalyst::Plugin::Authentication: 0.10018
  Catalyst::Plugin::ConfigLoader: 0.30
  Catalyst::Plugin::I18N: 0
  Catalyst::Plugin::Session: 0.32
  Catalyst::Plugin::Session::State::Cookie: 0
  Catalyst::Plugin::Session::Store::DBIC: 0
  Catalyst::Plugin::Session::Store::File: 0
  Catalyst::Plugin::StackTrace: 0
  Catalyst::Plugin::Static::Simple: 0.29
  Catalyst::Plugin::Unicode::Encoding: 0
  Catalyst::View::Email: 0
  Catalyst::View::TT: 0
  CatalystX::Component::Traits: 0.16
  CatalystX::LeakChecker: 0
  CatalystX::Profile: 0
  CatalystX::SimpleLogin: 0
  Class::Accessor: 0.34
  Class::Accessor::Chained: 0.01
  Class::Accessor::Grouped: 0.10006
  Class::Adapter: 1.08
  Class::Base: 0.04
  Class::C3: 0.23
  Class::C3::Adopt::NEXT: 0.13
  Class::C3::Componentised: 1.001000
  Class::Data::Inheritable: 0.08
  Class::ErrorHandler: 0.01
  Class::Inspector: 1.25
  Class::Load: 0.15
  Class::Load::XS: 0.04
  Class::Loader: 2.03
  Class::MakeMethods: 1.01
  Class::Method::Modifiers: 1.08
  Class::Singleton: 1.4
  Class::Unload: 0.07
  Class::XSAccessor: 1.13
  Clipboard: 0.13
  Clone: 0.31
  Compress::Bzip2: 2.09
  Compress::Raw::Bzip2: 2.042
  Compress::Raw::Zlib: 2.042
  Compress::unLZMA: 0.04
  Config::Any: 0.23
  Config::General: 2.50
  Config::INI::Reader: 0.019
  Config::MVP::Assembler: 2.200001
  Config::MVP::Reader::INI: 2.101461
  Config::Perl::V: 0.14
  Config::Tiny: 2.14
  Context::Preserve: 0.01
  Convert::ASCII::Armour: 1.4
  Convert::ASN1: 0.22
  Convert::Bencode: 1.03
  Convert::Bencode_XS: 0.06
  Convert::PEM: 0.08
  Crypt::CAST5_PP: 1.04
  Crypt::CBC: 2.30
  Crypt::DES: 2.05
  Crypt::DES_EDE3: 0.01
  Crypt::RIPEMD160: 0.05
  Crypt::Twofish: 2.14
  Cwd: 3.2701
  DBD::SQLite: 1.35
  DBI: 1.616
  DBIx::Class: 0.08196
  DBIx::Class::Cursor::Cached: 1.001002
  DBIx::Class::IntrospectableM2M: 0.001001
  DBIx::Class::Schema::Loader: 0.07010
  DBIx::RunSQL: 0.07
  DBIx::Simple: 1.35
  DBM::Deep: 2.0004
  Dancer: 1.3092
  Data::Buffer: 0.04
  Data::Compare: 1.22
  Data::Denter: 0.15
  Data::Dump: 1.21
  Data::Dump::Streamer: 2.32
  Data::Dumper: 2.131
  Data::Dumper::Concise: 2.020
  Data::Dumper::Names: 0.03
  Data::GUID: 0.046
  Data::OptList: 0.107
  Data::Page: 2.02
  Data::Random: 0.06
  Data::Section: 0.101621
  Data::Serializer: 0.59
  Data::Taxi: 0.96
  Data::UUID: 1.217
  Data::Visitor: 0.27
  Date::Format: 2.24
  Date::Tiny: 0
  DateTime: 0.72
  DateTime::Format::Atom: 1.0.2
  DateTime::Format::Mail: 0.3001
  DateTime::Format::RFC3339: 1.0.5
  DateTime::Format::W3CDTF: 0.06
  DateTime::Locale: 0.45
  DateTime::TimeZone: 1.42
  DateTime::Tiny: 0
  Debug::Client: 0.20
  Debug::ShowStuff: 1.13
  Declare::Constraints::Simple: 0.03
  Devel::Autoflush: 0.05
  Devel::Caller: 2.05
  Devel::Cover: 0.79
  Devel::Cycle: 1.11
  Devel::Declare: 0.006010
  Devel::Dumpvar: 1.06
  Devel::GlobalDestruction: 0.04
  Devel::LexAlias: 0.04
  Devel::NYTProf: 0
  Devel::PPPort: 3.20
  Devel::PartialDump: 0.15
  Devel::REPL: 1.003012
  Devel::Refactor: 0.05
  Devel::StackTrace: 1.27
  Devel::StackTrace::AsHTML: 0.11
  Devel::Symdump: 2.08
  Digest: 1.17
  Digest::BubbleBabble: 0.02
  Digest::MD2: 2.03
  Digest::Perl::MD5: 1.8
  Digest::SHA: 5.63
  Digest::SHA1: 2.13
  Dist::CheckConflicts: 0.02
  Dist::Zilla: 4.300007
  Email::Abstract: 3.004
  Email::Address: 1.895
  Email::Date::Format: 1.002
  Email::MIME: 1.910
  Email::MIME::ContentType: 1.015
  Email::MIME::Encodings: 1.313
  Email::MIME::Kit: 2.102010
  Email::MessageID: 1.402
  Email::Sender: 0.110003
  Email::Simple: 2.101
  Email::Valid: 0.187
  Encode: 2.44
  Encode::Locale: 1.02
  Env: 1.03
  Error: 0.17017
  Eval::Closure: 0.07
  Excel::Writer::XLSX: 0.46
  Exception::Base: 0.2401
  Exception::Class: 1.32
  Exporter: 5.65
  Exporter::Declare: 0.105
  ExtUtils::Depends: 0.304
  ExtUtils::MakeMaker: 6.62
  ExtUtils::Manifest: 1.60
  ExtUtils::ParseXS: 3.05
  ExtUtils::XSpp: 0.1602
  FCGI: 0.74
  Feed::Find: 0.07
  Fennec::Lite: 0.004
  File::Basename: 0
  File::ChangeNotify: 0.21
  File::Copy::Recursive: 0.37
  File::Find: 0
  File::Find::Rule: 0.33
  File::Glob: 0
  File::HomeDir: 0.98
  File::Listing: 6.03
  File::Next: 1.06
  File::Path: 2.08
  File::Remove: 1.51
  File::ShareDir: 1.03
  File::ShareDir::Install: 0.04
  File::Slurp: 9999.19
  File::Spec: 3.2701
  File::Spec::Functions: 3.2701
  File::Temp: 0.20
  File::Which: 1.09
  File::chmod: 0.32
  File::pushd: 1.001
  Filesys::Notify::Simple: 0.08
  Filter::Simple: 0.87
  FindBin: 0
  Format::Human::Bytes: 0.06
  FreezeThaw: 0.5001
  Getopt::Long: 0
  Getopt::Long::Descriptive: 0.090
  HTML::Entities: 3.57
  HTML::Form: 6.00
  HTML::Lint: 2.10
  HTML::Parser: 3.69
  HTML::Tagset: 3.20
  HTML::Template: 2.9
  HTML::TreeBuilder: 4.2
  HTTP::Body: 1.15
  HTTP::Cookies: 6.00
  HTTP::Daemon: 6.00
  HTTP::Date: 6.00
  HTTP::Lite: 2.3
  HTTP::Message: 6.02
  HTTP::Negotiate: 6.00
  HTTP::Request::AsCGI: 1.2
  HTTP::Server::Simple: 0.44
  HTTP::Server::Simple::PSGI: 0.14
  HTTP::Tiny: 0.016
  Hash::Merge: 0.12
  Hash::Merge::Simple: 0.051
  Hash::MultiValue: 0.10
  Hash::Util::FieldHash::Compat: 0.03
  Hook::LexWrap: 0.24
  IO::All: 0
  IO::CaptureOutput: 1.1102
  IO::Interactive: 0.0.6
  IO::Scalar: 0
  IO::Socket: 1.30
  IO::String: 1.08
  IO::Stringy: 2.110
  IO::TieCombine: 1.001
  IPC::Cmd: 0.76
  IPC::Open2: 0
  IPC::Open3: 0
  IPC::Run: 0.90
  IPC::Run3: 0.044
  IPC::System::Simple: 1.21
  Imager: 0.86
  JSON: 2.53
  JSON::PP: 2.27200
  JSON::Syck: 1.20
  JSON::XS: 2.32
  LWP: 5.815
  LWP::MediaTypes: 6.01
  LWP::Online: 1.08
  LWP::Protocol::https: 6.02
  LWP::Simple: 0
  LWP::UserAgent: 5.815
  Lexical::Persistence: 1.020
  Lingua::EN::Inflect: 1.893
  Lingua::EN::Inflect::Number: 1.1
  Lingua::EN::Inflect::Phrase: 0.12
  Lingua::EN::Tagger: 0.16
  Lingua::PT::Stemmer: 0.01
  Lingua::Stem: 0.84
  Lingua::Stem::Fr: 0.02
  Lingua::Stem::It: 0.02
  Lingua::Stem::Ru: 0.01
  Lingua::Stem::Snowball::Da: 1.01
  Lingua::Stem::Snowball::No: 1.2
  Lingua::Stem::Snowball::Se: 1.2
  List::MoreUtils: 0.33
  List::Util: 1.18
  Locale::Codes: 3.18
  Locale::Maketext: 1.19
  Locale::Msgfmt: 0.15
  Log::Contextual: 0.004001
  Log::Dispatch: 2.29
  Log::Dispatch::Array: 1.001
  Log::Dispatch::Configurator: 1.00
  Log::Dispatchouli: 2.005
  Log::Log4perl: 1.35
  MIME::Lite: 3.028
  MIME::Types: 1.34
  MRO::Compat: 0.11
  Mail::Address: 2.08
  Math::Complex: 1.58
  Math::Round: 0.06
  MemHandle: 0.07
  Memoize::ExpireLRU: 0.55
  Meta::Builder: 0.003
  MetaCPAN::API: 0.43
  Metabase::Client::Simple: 0.008
  Metabase::Fact::Hash: 0.020
  Mixin::Linewise::Readers: 0.003
  Modern::Perl: 1.20120130
  Module::Build: 0.3800
  Module::CoreList: 2.57
  Module::Find: 0.10
  Module::Implementation: 0.04
  Module::Install: 1.04
  Module::Install::ReadmeFromPod: 0.16
  Module::Load: 0.22
  Module::Load::Conditional: 0.46
  Module::Manifest: 1.08
  Module::Metadata: 1.000007
  Module::Refresh: 0.17
  Module::Runtime: 0.011
  Module::ScanDeps: 1.07
  Moo: 0.009013
  Moose: 2.0402
  Moose::Autobox: 0.11
  MooseX::App::Cmd: 0
  MooseX::AttributeHelpers: 0.23
  MooseX::ClassAttribute: 0
  MooseX::Clone: 0
  MooseX::ConfigFromFile: 0
  MooseX::Declare: 0
  MooseX::Emulate::Class::Accessor::Fast: 0.00903
  MooseX::Getopt: 0.39
  MooseX::GlobRef: 0.0701
  MooseX::InsideOut: 0.106
  MooseX::Iterator: 0
  MooseX::LazyLogDispatch: 0
  MooseX::LazyRequire: 0.07
  MooseX::Log::Log4perl: 0
  MooseX::LogDispatch: 1.2002
  MooseX::MarkAsMethods: 0.14
  MooseX::Meta::TypeConstraint::ForceCoercion: 0.01
  MooseX::Method::Signatures: 0
  MooseX::MethodAttributes::Inheritable: 0.27
  MooseX::NonMoose: 0.22
  MooseX::Object::Pluggable: 0.0011
  MooseX::OneArgNew: 0.002
  MooseX::POE: 0
  MooseX::Param: 0
  MooseX::Params::Validate: 0.16
  MooseX::Role::Parameterized: 1.00
  MooseX::Role::TraitConstructor: 0.01
  MooseX::Role::WithOverloading: 0.09
  MooseX::SemiAffordanceAccessor: 0.09
  MooseX::SetOnce: 0.200001
  MooseX::SimpleConfig: 0
  MooseX::Singleton: 0.29
  MooseX::Storage: 0.30
  MooseX::StrictConstructor: 0.19
  MooseX::Traits: 0.11
  MooseX::Traits::Pluggable: 0.10
  MooseX::Types: 0.31
  MooseX::Types::Common::Numeric: 0.001007
  MooseX::Types::DateTime: 0.07
  MooseX::Types::LoadableClass: 0.007
  MooseX::Types::Path::Class: 0.05
  MooseX::Types::Perl: 0.101341
  MooseX::Types::Set::Object: 0
  MooseX::Types::Structured: 0.28
  Mouse: 0.97
  Mozilla::CA: 20120118
  Net::HTTP: 6.01
  Net::SMTP::TLS: 0.12
  Net::Telnet: 3.03
  Number::Compare: 0.03
  OLE::Storage_Lite: 0.19
  ORLite: 1.96
  ORLite::Migrate: 1.10
  Object::Accessor: 0.42
  Object::Signature: 1.07
  PAR: 1.002
  PAR::Dist: 0.48
  PAR::Dist::FromPPD: 0.03
  PAR::Dist::InstallPPD: 0.02
  PAR::Repository::Client: 0.25
  PAR::Repository::Query: 0.14
  PHP::Serialization: 0.34
  POD2::Base: 0.043
  POE: 1.350
  POE::Test::Loops: 1.350
  POSIX: 0
  PPI: 1.215
  PPI::HTML: 1.08
  PPIx::EditorTools: 0.15
  PPIx::Regexp: 0.025
  PPIx::Utilities::Node: 1.001000
  Package::DeprecationManager: 0.11
  Package::Stash: 0.33
  Package::Stash::XS: 0.25
  PadWalker: 1.93
  Padre::Plugin::Moose: 0.20
  Padre::Plugin::Snippet: 0.01
  Params::Check: 0.32
  Params::Classify: 0.013
  Params::Util: 1.04
  Params::Validate: 1.05
  Parse::Binary: 0.11
  Parse::ErrorString::Perl: 0.15
  Parse::ExuberantCTags: 1.02
  Parse::Method::Signatures: 1.003014
  Parse::RecDescent: 1.967003
  Path::Class: 0.24
  Perl6::Junction: 1.400000
  Perl::Critic: 1.117
  Perl::PrereqScanner: 1.009
  Perl::Tidy: 20101217
  Perl::Version: 1.011
  Plack: 0.9985
  Plack::Middleware::ReverseProxy: 0.11
  Plack::Test::ExternalServer: 0.01
  Pod::Abstract: 0.20
  Pod::Coverage: 0.22
  Pod::Coverage::Moose: 0
  Pod::Eventual: 0.093330
  Pod::Functions: 0
  Pod::POM: 0.27
  Pod::Perldoc: 3.15
  Pod::Readme: 0
  Pod::Simple: 3.19
  Pod::Simple::XHTML: 3.04
  Pod::Spell: 1.01
  Probe::Perl: 0.01
  Readonly: 1.03
  Readonly::XS: 1.05
  Role::HasMessage: 0.005
  Role::Identifiable::HasIdent: 0.005
  SOAP::Lite: 0.714
  SQL::Abstract: 1.72
  SQL::Translator: 0.11010
  SUPER: 1.17
  SVG: 2.50
  Scope::Guard: 0.20
  Scope::Upper: 0.18
  Set::Object: 0
  Smart::Comments: 0
  Software::License: 0.103004
  Sort::Versions: 1.5
  Spiffy: 0.30
  Spreadsheet::ParseExcel: 0.59
  Spreadsheet::ParseExcel::Simple: 0
  Spreadsheet::WriteExcel: 2.37
  Spreadsheet::WriteExcel::Simple: 0
  Spreadsheet::WriteExcelXML: 0.13
  StackTrace::Auto: 0.102080
  Storable: 2.30
  String::CRC32: 1.4
  String::CamelCase: 0.02
  String::Errf: 0.006
  String::Escape: 2010.002
  String::Flogger: 1.101241
  String::Format: 1.16
  String::Formatter: 0.102082
  String::Random: 0.22
  String::RewritePrefix: 0.006
  String::ToIdentifier::EN: 0.07
  Sub::Exporter: 0.982
  Sub::Exporter::ForMethods: 0.100050
  Sub::Exporter::GlobExporter: 0.002
  Sub::Identify: 0.04
  Sub::Install: 0.925
  Sub::Name: 0.05
  Sub::Uplevel: 0.22
  Symbol::Util: 0.0202
  Syntax::Keyword::Gather: 1.001000
  Sys::Hostname: 0
  Sys::Syslog: 0.29
  Task::Kensho::Async: 0.28
  Task::Kensho::Config: 0.28
  Task::Kensho::Email: 0.28
  Task::Kensho::Logging: 0.01
  Task::Kensho::OOP: 0.28
  Task::Kensho::Testing: 0.28
  Task::Kensho::Toolchain: 0.28
  Task::Kensho::WebCrawling: 0.28
  Task::Kensho::XML: 0.28
  Task::Weaken: 1.04
  Template: 2.24
  Template::Tiny: 0.12
  Term::ANSIColor: 3.01
  Term::ProgressBar::Simple: 0
  Term::ReadLine: 0
  Test::Assert: 0.0504
  Test::Base: 0.60
  Test::Class: 0.36
  Test::DatabaseRow: 2.02
  Test::Deep: 0.108
  Test::Differences: 0.61
  Test::Distribution: 2.00
  Test::Exception: 0.31
  Test::Fatal: 0.008
  Test::HTTP::Server::Simple: 0.11
  Test::Harness: 0
  Test::LeakTrace: 0.14
  Test::LongString: 0.15
  Test::Manifest: 1.23
  Test::Memory::Cycle: 1.04
  Test::Mock::LWP: 0.06
  Test::MockModule: 0.05
  Test::MockObject: 1.20110612
  Test::Most: 0.25
  Test::NoWarnings: 1.03
  Test::Object: 0.07
  Test::Output: 1.01
  Test::Perl::Critic: 1.02
  Test::Pod: 1.45
  Test::Pod::Coverage: 1.08
  Test::Reporter: 1.58
  Test::Reporter::Transport::Metabase: 1.999008
  Test::Requires: 0.06
  Test::Script: 1.07
  Test::SharedFork: 0.19
  Test::Simple: 0.88
  Test::SubCalls: 1.09
  Test::TCP: 1.15
  Test::Taint: 1.04
  Test::Tester: 0.107
  Test::TinyMocker: 0.03
  Test::Trap: 0.2.1
  Test::Unit::Lite: 0.12
  Test::WWW::Mechanize: 1.38
  Test::WWW::Mechanize::Catalyst: 0
  Test::WWW::Selenium: 1.32
  Test::Warn: 0.24
  Test::Without::Module: 0.17
  Test::use::ok: 0.02
  Text::Balanced: 2.01
  Text::CSV: 1.21
  Text::CSV_XS: 0.86
  Text::Diff: 1.41
  Text::FindIndent: 0.10
  Text::German: 0.06
  Text::Glob: 0.09
  Text::Markdown: 0
  Text::Patch: 1.8
  Text::SimpleTable: 2.03
  Text::Template: 1.45
  Text::Unidecode: 0.04
  Tie::EncryptedHash: 1.24
  Tie::IxHash: 1.22
  Tie::ToObject: 0.03
  Time::HiRes: 1.9724
  Time::Piece: 0
  Time::Seconds: 0
  Time::Tiny: 0
  Tree::DAG_Node: 1.06
  Tree::Simple: 1.18
  Tree::Simple::Visitor::FindByPath: 0.03
  Try::Tiny: 0.11
  UNIVERSAL::can: 1.20110617
  UNIVERSAL::isa: 1.20110614
  URI: 1.59
  URI::Fetch: 0.09
  URI::Find: 20111103
  Unicode::Collate: 0.84
  Unicode::Normalize: 1.13
  Variable::Magic: 0.48
  WWW::Mechanize: 1.72
  WWW::Mechanize::TreeBuilder: 1.10003
  WWW::Pastebin::PastebinCom::Create: 0.004
  WWW::RobotRules: 6.01
  Web::Simple: 0.012
  XML::Atom: 0.41
  XML::Dumper: 0.81
  XML::Feed: 0.46
  XML::Filter::BufferText: 1.01
  XML::Generator::PerlData: 0.91
  XML::LibXML: 1.88
  XML::LibXSLT: 1.75
  XML::NamespaceSupport: 1.11
  XML::Parser: 2.41
  XML::RSS: 1.49
  XML::SAX::Base: 1.08
  XML::SAX::Writer: 0.53
  XML::Simple: 2.18
  XML::Writer: 0.615
  XML::XPath: 1.13
  XSLoader: 0.15
  YAML: 0.80
  YAML::Syck: 0
  YAML::Tiny: 1.50
  YAML::XS: 0.38
  aliased: 0.30
  autobox: 2.75
  autodie: 0
  bignum: 0.29
  common::sense: 3.4
  constant::boolean: 0.02
  namespace::autoclean: 0.13
  namespace::clean: 0.22
  perl: 5.008
  pip: 1.19
  pler: 1.06
  strictures: 1.002002
  syntax: 0.003
  utf8: 0
  version: 0.95
  warnings::illegalproto: 0.001000
resources:
  license: http://dev.perl.org/licenses/
  repository: https://github.com/dwimperl/Task-DWIM
version: 0.05
