---
abstract: 'A Task module for DWIM Perl L<http://dwimperl.com/>'
author:
  - 'Gabor Szabo <szabgab@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Task-DWIM
no_index:
  directory:
    - inc
    - t
requires:
  Algorithm::Diff: 1.19
  App::Ack: 0
  App::cpanminus: 0.9923
  B::Deparse: 0
  CGI: 3.47
  CGI::FormBuilder::Source::Perl: 0
  CHI: 0
  CPAN::Uploader: 0
  Capture::Tiny: 0.06
  Carp::Always: 0
  Catalyst: 5.80
  Catalyst::Action::REST: 0
  Catalyst::ActionRole::ACL: 0
  Catalyst::Authentication::Credential::HTTP: 0
  Catalyst::Authentication::Store::DBIx::Class: 0
  Catalyst::Component::InstancePerContext: 0
  Catalyst::Controller::ActionRole: 0
  Catalyst::Devel: 1.26
  Catalyst::Manual: 5.80
  Catalyst::Model::Adaptor: 0
  Catalyst::Model::DBIC::Schema: 0
  Catalyst::Plugin::Authentication: 0
  Catalyst::Plugin::ConfigLoader: 0
  Catalyst::Plugin::I18N: 0
  Catalyst::Plugin::Session: 0
  Catalyst::Plugin::Session::State::Cookie: 0
  Catalyst::Plugin::Session::Store::DBIC: 0
  Catalyst::Plugin::Session::Store::File: 0
  Catalyst::Plugin::StackTrace: 0
  Catalyst::Plugin::Static::Simple: 0
  Catalyst::Plugin::Unicode::Encoding: 0
  Catalyst::View::Email: 0
  Catalyst::View::TT: 0
  CatalystX::Component::Traits: 0
  CatalystX::LeakChecker: 0
  CatalystX::Profile: 0
  CatalystX::SimpleLogin: 0
  Class::Adapter: 1.05
  Class::Inspector: 1.22
  Class::XSAccessor: 1.13
  Config::Any: 0
  Config::General: 0
  Cwd: 3.2701
  DBD::SQLite: 1.35
  DBI: 1.58
  DBIx::Class: 0
  DBIx::Class::Schema::Loader: 0
  Data::Dumper: 0
  Date::Tiny: 0
  DateTime: 0
  DateTime::Tiny: 0
  Debug::Client: 0.20
  Devel::Cover: 0
  Devel::Dumpvar: 0.04
  Devel::NYTProf: 0
  Devel::REPL: 0
  Devel::Refactor: 0.05
  Dist::Zilla: 0
  Email::MIME::Kit: 0
  Email::Sender: 0
  Email::Simple: 0
  Email::Valid: 0
  Encode: 2.26
  ExtUtils::MakeMaker: 6.56
  ExtUtils::Manifest: 1.56
  FCGI: 0
  File::Basename: 0
  File::Copy::Recursive: 0.37
  File::Find: 0
  File::Find::Rule: 0.30
  File::Glob: 0
  File::HomeDir: 0.98
  File::Path: 2.08
  File::Remove: 1.49
  File::ShareDir: 1.00
  File::Spec: 3.2701
  File::Spec::Functions: 3.2701
  File::Temp: 0.20
  File::Which: 1.08
  File::pushd: 1.00
  FindBin: 0
  Getopt::Long: 0
  HTML::Entities: 3.57
  HTML::Parser: 3.58
  HTTP::Lite: 0
  IO::All: 0
  IO::Scalar: 0
  IO::Socket: 1.30
  IO::String: 1.08
  IPC::Open2: 0
  IPC::Open3: 0
  IPC::Run: 0.83
  JSON: 2.0
  JSON::PP: 0
  JSON::XS: 2.29
  LWP: 5.815
  LWP::Simple: 0
  LWP::UserAgent: 5.815
  List::MoreUtils: 0.22
  List::Util: 1.18
  Log::Contextual: 0
  Log::Dispatch: 0
  Log::Log4perl: 0
  MIME::Types: 0
  Modern::Perl: 0
  Module::Build: 0.3603
  Module::CoreList: 2.22
  Module::Install: 0
  Module::Manifest: 0.07
  Moose::Autobox: 0
  MooseX::App::Cmd: 0
  MooseX::ClassAttribute: 0
  MooseX::Clone: 0
  MooseX::ConfigFromFile: 0
  MooseX::Declare: 0
  MooseX::Getopt: 0
  MooseX::GlobRef: 0
  MooseX::InsideOut: 0
  MooseX::Iterator: 0
  MooseX::LazyLogDispatch: 0
  MooseX::Log::Log4perl: 0
  MooseX::LogDispatch: 0
  MooseX::Method::Signatures: 0
  MooseX::NonMoose: 0
  MooseX::Object::Pluggable: 0
  MooseX::POE: 0
  MooseX::Param: 0
  MooseX::Params::Validate: 0
  MooseX::Role::Parameterized: 0
  MooseX::Role::TraitConstructor: 0
  MooseX::SemiAffordanceAccessor: 0
  MooseX::SimpleConfig: 0
  MooseX::Singleton: 0
  MooseX::Storage: 0
  MooseX::StrictConstructor: 0
  MooseX::Traits: 0
  MooseX::Types: 0
  MooseX::Types::DateTime: 0
  MooseX::Types::Path::Class: 0
  MooseX::Types::Set::Object: 0
  MooseX::Types::Structured: 0
  ORLite: 1.96
  ORLite::Migrate: 1.10
  POD2::Base: 0.043
  POE: 0
  POSIX: 0
  PPI: 1.213
  PPIx::EditorTools: 0.13
  PPIx::Regexp: 0.011
  Params::Util: 0.33
  Parse::ErrorString::Perl: 0.14
  Parse::ExuberantCTags: 1.00
  Perl::Critic: 0
  Perl::Tidy: 0
  Perl::Version: 0
  Plack: 0
  Pod::Abstract: 0.16
  Pod::Coverage::Moose: 0
  Pod::Functions: 0
  Pod::POM: 0.17
  Pod::Perldoc: 3.15
  Pod::Readme: 0
  Pod::Simple: 3.07
  Pod::Simple::XHTML: 3.04
  Probe::Perl: 0.01
  SQL::Translator: 0
  Set::Object: 0
  Smart::Comments: 0
  Software::License: 0
  Sort::Versions: 1.5
  Spreadsheet::ParseExcel::Simple: 0
  Spreadsheet::WriteExcel::Simple: 0
  Storable: 2.16
  Sys::Hostname: 0
  Template: 0
  Template::Tiny: 0.11
  Term::ProgressBar::Simple: 0
  Term::ReadLine: 0
  Test::Deep: 0
  Test::Exception: 0.27
  Test::Fatal: 0
  Test::Harness: 0
  Test::Memory::Cycle: 0
  Test::MockObject: 1.09
  Test::Most: 0
  Test::NoWarnings: 0.084
  Test::Pod: 0
  Test::Pod::Coverage: 0
  Test::Requires: 0
  Test::Script: 1.07
  Test::Simple: 0.88
  Test::WWW::Mechanize::Catalyst: 0
  Test::Warn: 0.24
  Text::Balanced: 2.01
  Text::CSV_XS: 0
  Text::Diff: 1.41
  Text::FindIndent: 0.10
  Text::Markdown: 0
  Text::Patch: 1.8
  Time::HiRes: 1.9718
  Time::Piece: 0
  Time::Seconds: 0
  Time::Tiny: 0
  Try::Tiny: 0
  URI: 0
  WWW::Mechanize: 0
  WWW::Mechanize::TreeBuilder: 0
  XML::Atom: 0
  XML::Generator::PerlData: 0
  XML::LibXML: 0
  XML::LibXSLT: 0
  XML::RSS: 0
  XML::SAX: 0
  XML::SAX::Writer: 0
  XML::XPath: 0
  YAML: 0
  YAML::Syck: 0
  YAML::Tiny: 1.32
  autodie: 0
  namespace::autoclean: 0
  perl: 5.008
  utf8: 0
  version: 0.95
resources:
  license: http://dev.perl.org/licenses/
  repository: https://github.com/dwimperl/Task-DWIM
version: 0.04
