---
abstract: 'A Task module for DWIM Perl L<http://dwimperl.com/>'
author:
  - 'Gabor Szabo <szabgab@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Perl::Version: 1.011
  Test::More: 0.42
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Task-DWIM
no_index:
  directory:
    - inc
    - t
requires:
  Task::DWIM::Async: 0.07
  Task::DWIM::CLI: 0.07
  Task::DWIM::CPAN: 0.07
  Task::DWIM::Catalyst: 0.07
  Task::DWIM::Compression: 0.07
  Task::DWIM::Config: 0.07
  Task::DWIM::Dancer: 0.07
  Task::DWIM::Database: 0.07
  Task::DWIM::DateTime: 0.07
  Task::DWIM::Desktop: 0.07
  Task::DWIM::DistZilla: 0.07
  Task::DWIM::Email: 0.07
  Task::DWIM::Encryption: 0.07
  Task::DWIM::Exceptions: 0.07
  Task::DWIM::Logging: 0.07
  Task::DWIM::Modules: 0.07
  Task::DWIM::Moose: 0.07
  Task::DWIM::NoWindows: 0.07
  Task::DWIM::OOP: 0.07
  Task::DWIM::Science: 0.07
  Task::DWIM::Serialization: 0.07
  Task::DWIM::Spreadsheet: 0.07
  Task::DWIM::Test: 0.07
  Task::DWIM::Web: 0.07
  Task::DWIM::WebClient: 0.07
  Task::DWIM::Windows: 0.07
  Task::DWIM::XML: 0.07
  perl: 5.008
resources:
  license: http://dev.perl.org/licenses/
  repository: https://github.com/dwimperl/Task-DWIM
version: 0.07
