---
abstract: 'A Task module for DWIM Perl L<http://dwimperl.com/>'
author:
  - 'Gabor Szabo <szabgab@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Task-DWIM
no_index:
  directory:
    - inc
    - t
requires:
  App::cpanminus: 0
  CGI: 0
  CGI::FormBuilder::Source::Perl: 0
  Data::Dumper: 0
  DateTime: 0
  Devel::Cover: 0
  Encode: 0
  File::Find: 0
  Getopt::Long: 0
  JSON: 2.0
  JSON::PP: 0
  JSON::XS: 0
  Log::Contextual: 0
  Log::Dispatch: 0
  Log::Log4perl: 0
  MIME::Types: 0
  Moose::Autobox: 0
  MooseX::App::Cmd: 0
  MooseX::ClassAttribute: 0
  MooseX::Clone: 0
  MooseX::ConfigFromFile: 0
  MooseX::Daemonize: 0
  MooseX::Declare: 0
  MooseX::Getopt: 0
  MooseX::GlobRef: 0
  MooseX::InsideOut: 0
  MooseX::Iterator: 0
  MooseX::LazyLogDispatch: 0
  MooseX::Log::Log4perl: 0
  MooseX::LogDispatch: 0
  MooseX::Method::Signatures: 0
  MooseX::NonMoose: 0
  MooseX::Object::Pluggable: 0
  MooseX::POE: 0
  MooseX::Param: 0
  MooseX::Params::Validate: 0
  MooseX::Role::Cmd: 0
  MooseX::Role::Parameterized: 0
  MooseX::Role::TraitConstructor: 0
  MooseX::SemiAffordanceAccessor: 0
  MooseX::SimpleConfig: 0
  MooseX::Singleton: 0
  MooseX::Storage: 0
  MooseX::StrictConstructor: 0
  MooseX::Traits: 0
  MooseX::Types: 0
  MooseX::Types::DateTime: 0
  MooseX::Types::Path::Class: 0
  MooseX::Types::Set::Object: 0
  MooseX::Types::Structured: 0
  MooseX::Workers: 0
  POE: 0
  Plack: 0
  Pod::Coverage::Moose: 0
  Set::Object: 0
  Sys::Hostname: 0
  Template: 0
  Test::Deep: 0
  Test::Fatal: 0
  Test::Harness: 0
  Test::Memory::Cycle: 0
  Test::Most: 0
  Test::NoWarnings: 0
  Test::Pod: 0
  Test::Pod::Coverage: 0
  Test::Requires: 0
  Test::Simple: 0
  Text::Markdown: 0
  Time::HiRes: 0
  Time::Piece: 0
  Time::Seconds: 0
  Try::Tiny: 0
  XML::Atom: 0
  XML::RSS: 0
  XML::XPath: 0
  YAML: 0
  YAML::Syck: 0
  autodie: 0
  namespace::autoclean: 0
  perl: 5.008
  utf8: 0
  version: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: https://github.com/dwimperl/Task-DWIM
version: 0.02
